spring:
  application:
    name: collab

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  docker:
    compose:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9093}

    security:
      protocol: SASL_SSL

    ssl:
      trust-store-location: classpath:kafka.truststore.p12
      trust-store-password: ${KAFKA_SSL_TRUSTSTORE_PASSWORD}
      trust-store-type: PKCS12

    properties:
      "[sasl.mechanism]": SCRAM-SHA-512
      "[sasl.jaas.config]": ${KAFKA_PRODUCER_SASL_JAAS_CONFIG}
      "[ssl.endpoint.identification.algorithm]": ""

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:collab-api}
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  kafka:
    topics:
      collaborator-created: collab.collaborator.created
      collaborator-updated: collab.collaborator.updated
      collaborator-deleted: collab.collaborator.deleted
      department-created: collab.department.created
      department-updated: collab.department.updated
      department-deleted: collab.department.deleted